name: Docker Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign release version from version.properties to Env variable
        run: |
           cat src/firebolt_cli/__init__.py | awk -F'"' '{ print $2}' >> $FIREBOLT_CLI_VERSION

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'ghcr.io/firebolt-db/firebolt-cli:{{ $env.FIREBOLT_CLI_VERSION }}'
